### ISSUE TITLE
Clarification about "+5"

### ISSUE THREAD

**Issue by jobedylbas** [pcolby/scripts#1]
I was reading about how to measure cpu use and I found your code, but I was wondering
why you sum 5 on  $DIFF_TOTAL. Thanks. 
https://github.com/pcolby/scripts/blob/f13d1026d98469f505cfe6abfc7008d495cd36ce/cpu.sh#L21

**Comment by pcolby** [comment]
Hi @jobedylbas, this is explained in [my blog post](http://colby.id.au/calculating-cpu-usage-from-proc-stat/):

> Notice the way the percentage is calculated by multiplying by 1000, and then dividing by 10 at the end, instead of the "normal" approach of multiplying by 100. This is actually a cunning way of rounding off :) See the way I add 5 just before the divide by 10? So, for example, if the percentage was 45.6% then BASH would truncate the result to 45%. But, by multiplying by 1000 (instead of 100), and adding 5, the result is 461 (ie 456+5), which, when divided by 10 at the end, yields the correctly rounded result of 46% :)

Basically, its a lazy (efficient) way of round numbers using Bash's integer truncation.

Cheers.

**Comment by jobedylbas** [comment]
Oh, thanks, unfortunately I didn't saw the link for the blog. Since your answer me i'll close this issue. 

Thank you again.
