### ISSUE TITLE
cpu.sh: your "total" includes guest (and guest_nice) twice

### ISSUE THREAD

**Issue by jaimet** [pcolby/scripts#2]
Your sum to create the total cpu usage includes both "user" *and* "guest", but "user" *already includes* guest, as per:

https://unix.stackexchange.com/questions/178045
https://github.com/netdata/netdata/issues/729
https://lkml.org/lkml/2008/6/23/65
https://www.opsdash.com/blog/cpu-usage-linux.html

The same "logic" also applies to "nice" and "guest_nice".

HTH, Jaime

**Comment by pcolby** [comment]
Thanks @jaimet!! I've definitely learned something new here! :smile:  Thanks for taking the time to report it.

I'll update the script to allow for the overlapped fields soon.

Thanks again!
